create table public.access_events_read_model (
  id uuid primary key default gen_random_uuid(),
  access_event_id uuid,
  booking_id uuid,
  office_id uuid,
  actor_id uuid,
  occurred_at timestamptz not null,
  date_label text not null,
  time_label text not null,
  actor_display_id text not null,
  actor_display_name text not null,
  actor_display_type text not null,
  location_label text not null,
  access_method text not null,
  status text not null,
  status_label text not null,
  is_security_alert boolean not null default false,
  is_anomaly boolean not null default false,
  reason_label text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint access_events_read_model_date_label_not_empty_check check (date_label <> ''),
  constraint access_events_read_model_time_label_not_empty_check check (time_label <> ''),
  constraint access_events_read_model_actor_display_id_not_empty_check check (actor_display_id <> ''),
  constraint access_events_read_model_actor_display_name_not_empty_check check (actor_display_name <> ''),
  constraint access_events_read_model_actor_display_type_not_empty_check check (actor_display_type <> ''),
  constraint access_events_read_model_location_label_not_empty_check check (location_label <> ''),
  constraint access_events_read_model_access_method_not_empty_check check (access_method <> ''),
  constraint access_events_read_model_status_not_empty_check check (status <> ''),
  constraint access_events_read_model_status_label_not_empty_check check (status_label <> '')
);
