select private.set_actor_context(
  null,
  'SYSTEM'::public.actor_type,
  'phase_8b_booking_status_transitions_seed'
);

insert into public.booking_status_transitions (
  from_status,
  to_status,
  allowed_actor_types
)
values
  (
    'PENDING_APPROVAL'::public.booking_status,
    'APPROVED'::public.booking_status,
    array[
      'OWNER'::public.actor_type,
      'OPERATOR'::public.actor_type,
      'ADMIN'::public.actor_type
    ]
  ),
  (
    'PENDING_APPROVAL'::public.booking_status,
    'REJECTED'::public.booking_status,
    array[
      'OWNER'::public.actor_type,
      'OPERATOR'::public.actor_type,
      'ADMIN'::public.actor_type
    ]
  ),
  (
    'PENDING_APPROVAL'::public.booking_status,
    'CANCELLED'::public.booking_status,
    array[
      'USER'::public.actor_type,
      'OWNER'::public.actor_type,
      'OPERATOR'::public.actor_type,
      'ADMIN'::public.actor_type
    ]
  ),
  (
    'APPROVED'::public.booking_status,
    'PAYMENT_PENDING'::public.booking_status,
    array[
      'OWNER'::public.actor_type,
      'OPERATOR'::public.actor_type,
      'ADMIN'::public.actor_type,
      'SYSTEM'::public.actor_type
    ]
  ),
  (
    'APPROVED'::public.booking_status,
    'CANCELLED'::public.booking_status,
    array[
      'USER'::public.actor_type,
      'OWNER'::public.actor_type,
      'OPERATOR'::public.actor_type,
      'ADMIN'::public.actor_type
    ]
  ),
  (
    'PAYMENT_PENDING'::public.booking_status,
    'CONFIRMED'::public.booking_status,
    array[
      'SYSTEM'::public.actor_type,
      'JOB'::public.actor_type,
      'ADMIN'::public.actor_type
    ]
  ),
  (
    'PAYMENT_PENDING'::public.booking_status,
    'EXPIRED'::public.booking_status,
    array[
      'JOB'::public.actor_type,
      'SYSTEM'::public.actor_type,
      'ADMIN'::public.actor_type
    ]
  ),
  (
    'PAYMENT_PENDING'::public.booking_status,
    'CANCELLED'::public.booking_status,
    array[
      'USER'::public.actor_type,
      'OWNER'::public.actor_type,
      'OPERATOR'::public.actor_type,
      'ADMIN'::public.actor_type
    ]
  ),
  (
    'CONFIRMED'::public.booking_status,
    'CHECKED_IN'::public.booking_status,
    array[
      'USER'::public.actor_type,
      'OWNER'::public.actor_type,
      'OPERATOR'::public.actor_type,
      'SYSTEM'::public.actor_type,
      'ADMIN'::public.actor_type
    ]
  ),
  (
    'CONFIRMED'::public.booking_status,
    'NO_SHOW'::public.booking_status,
    array[
      'JOB'::public.actor_type,
      'SYSTEM'::public.actor_type,
      'ADMIN'::public.actor_type
    ]
  ),
  (
    'CONFIRMED'::public.booking_status,
    'CANCELLED'::public.booking_status,
    array[
      'USER'::public.actor_type,
      'OWNER'::public.actor_type,
      'OPERATOR'::public.actor_type,
      'ADMIN'::public.actor_type
    ]
  ),
  (
    'CHECKED_IN'::public.booking_status,
    'CHECKED_OUT'::public.booking_status,
    array[
      'USER'::public.actor_type,
      'OWNER'::public.actor_type,
      'OPERATOR'::public.actor_type,
      'SYSTEM'::public.actor_type,
      'ADMIN'::public.actor_type
    ]
  ),
  (
    'CHECKED_IN'::public.booking_status,
    'OVERSTAY'::public.booking_status,
    array[
      'JOB'::public.actor_type,
      'SYSTEM'::public.actor_type,
      'OWNER'::public.actor_type,
      'OPERATOR'::public.actor_type,
      'ADMIN'::public.actor_type
    ]
  ),
  (
    'OVERSTAY'::public.booking_status,
    'CHECKED_OUT'::public.booking_status,
    array[
      'USER'::public.actor_type,
      'OWNER'::public.actor_type,
      'OPERATOR'::public.actor_type,
      'SYSTEM'::public.actor_type,
      'ADMIN'::public.actor_type
    ]
  ),
  (
    'CHECKED_OUT'::public.booking_status,
    'COMPLETED'::public.booking_status,
    array[
      'JOB'::public.actor_type,
      'SYSTEM'::public.actor_type,
      'OWNER'::public.actor_type,
      'OPERATOR'::public.actor_type,
      'ADMIN'::public.actor_type
    ]
  ),
  (
    'COMPLETED'::public.booking_status,
    'REFUNDED'::public.booking_status,
    array[
      'SYSTEM'::public.actor_type,
      'JOB'::public.actor_type,
      'ADMIN'::public.actor_type
    ]
  ),
  (
    'CANCELLED'::public.booking_status,
    'REFUNDED'::public.booking_status,
    array[
      'SYSTEM'::public.actor_type,
      'JOB'::public.actor_type,
      'ADMIN'::public.actor_type
    ]
  )
on conflict (from_status, to_status)
do update set
  allowed_actor_types = excluded.allowed_actor_types;

select private.clear_actor_context();
